---
version: 1
labels:
  - label: 'small'
    size-below: 10
  - label: 'medium'
    size-above: 9
    size-below: 200
  - label: 'large'
    size-above: 200
  - label: 'documentation'
    files:
      - '.+.md'
  - label: 'config'
    files:
      - '.github'
      - '.autorc'
      - '.eslintrc'
      - '.eslintignore'
      - '.prettierrc'
      - '.prettierignore'
      - '.all-contributorsrc'
      - 'environments'
      - '.gitignore'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'package.json'
      - '.dockerignore'
      - '.gitignore'
  - label: 'code'
    files:
      - 'src'
