version: "3"

services:
  chartmuseum:
    image: ghcr.io/helm/chartmuseum:v0.16.0
    ports:
      - "8080:8080"
    environment:
      DEBUG: 1
      STORAGE: "local"
      STORAGE_LOCAL_ROOTDIR: "/tmp/charts"
    #volumes:
    #  - './charts:/charts'
