name: Check Required Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

permissions:
  actions: write
  checks: write
  issues: write
  pull-requests: write
  statuses: write

jobs:
  label:
    # do not run for prerelease branches
    if: github.head_ref != 'next' && github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: ejhayes/github-action-required-labels@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "major,minor,patch,skip-release,internal"
