name: Open Issues for TODO Comments

on:
  push:
    branches:
      - main
      - master
      - next

permissions:
  actions: write
  checks: write
  contents: read
  issues: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .git/hooks
      - name: Run tdg-github-action
        uses: ejhayes/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION_ASSET_URL: 'https://github.com/ejhayes/tdg-github-action/releases/latest/download/action.tar.gz'
